#
# 	Copyright 2020 Cristina Dinescu
# 	Licensed under the Apache License, Version 2.0 (the "License");
# 	you may not use this file except in compliance with the License.
# 	You may obtain a copy of the License at
# 		http://www.apache.org/licenses/LICENSE-2.0
# 	Unless required by applicable law or agreed to in writing, software
# 	distributed under the License is distributed on an "AS IS" BASIS,
# 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# 	See the License for the specific language governing permissions and
# 	limitations under the License.
#
#
usda:
  search:
    url: https://api.nal.usda.gov/ndb

api:
  key: r2zVHijDn5Q31pBPsS14i8kxKE3ayyOBKaxaJtWc

max:
  results:
    per:
      query: 5

response:
  format: json

eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq
  zipkin:
    base-url:
      - http://zipkin-server:9411/

sleuth:
  sampler:
    probability: 1.0
